development:
  bucket: myfragments-dev
  access_key_id: <%= ENV["ACCESS_KEY_ID"] %>
  secret_access_key: <%= ENV["SECRET_ACCESS_KEY"] %>
  s3_host_name: s3-ap-northeast-1.amazonaws.com
 
production:
  bucket: myfragments
  access_key_id: <%= ENV["ACCESS_KEY_ID"] %>
  secret_access_key: <%= ENV["SECRET_ACCESS_KEY"] %>
  s3_host_name: s3-ap-northeast-1.amazonaws.com
 
test:
  bucket: myfragments-dev
  access_key_id: <%= ENV["ACCESS_KEY_ID"] %>
  secret_access_key: <%= ENV["SECRET_ACCESS_KEY"] %>
  s3_host_name: s3-ap-northeast-1.amazonaws.com
